package com.holmes.ponderosa.ui.action;

import android.support.annotation.StringRes;
import android.support.v7.widget.RecyclerView;
import java.util.List;
import rx.Observable;
import rx.Subscription;
import rx.functions.Action1;

public interface ActionPresenter {
  @StringRes int getActionTitle();

  RecyclerView.Adapter getAdapter();

  Observable<List<String>> getFilterOptions();

  /**
   * @param countAction subscribe this action to the Observable. This should be the number of items returned.
   * @return the subscriptions generated by the Presenter.
   */
  Subscription loadData(Observable<String> selectedFilter, Action1<Integer> countAction);
}
