package com.holmes.ponderosa.ui.action;

import android.support.v7.widget.RecyclerView;
import rx.Subscription;
import rx.functions.Action1;

public interface ActionPresenter {
  RecyclerView.Adapter getAdapter();

  /**
   * @param countAction subscribe this action to the Observable. This should be the number of items returned.
   * @return the subscriptions generated by the Presenter.
   */
  Subscription loadData(Action1<Integer> countAction);
}
