package com.holmes.ponderosa.ui.action;

import android.support.annotation.StringRes;
import android.support.v7.widget.RecyclerView;
import io.reactivex.Observable;
import io.reactivex.disposables.Disposable;
import io.reactivex.functions.Consumer;
import java.util.List;

public interface ActionPresenter {
  @StringRes int getActionTitle();

  RecyclerView.Adapter getAdapter();

  Observable<List<String>> getFilterOptions();

  /**
   * @param countAction subscribe this action to the Observable. This should be the number of items returned.
   * @return the subscriptions generated by the Presenter.
   */
  Disposable loadData(Observable<String> selectedFilter, Consumer<Integer> countAction);
}
